<a href="https://colab.research.google.com/github/Semhylmz/YapaySinirAgileSiniflandirma/blob/main/Siniflandirma.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')  #google drive ile colabrotary bağlayarak veri setini drive içine aktardım ve oradan eriştim.

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd


In [ ]:
data = pd.read_csv("/content/drive/MyDrive/data/data_456.csv") #google drive'da olan veri setinin yolunu belirterek eriştim.

In [ ]:
data.shape #veri kümesindeki meta veriler

(126, 7)

In [ ]:
data.drop(columns = "Unnamed: 0", inplace = True) #Unnamed isimli etiketleri ayırdım
data.head() #ilk n satırı döndürdü

ozellik-1  ozellik-2  ozellik-3  ozellik-4  ozellik-5  cikis
0  -8.129682  -6.193360   5.296303   8.955262  -3.266606      1
1   9.705815  -5.275625   6.012196  -5.893469  -6.676234      0
2  -7.944387  -6.130736   4.100220   9.626914  -4.119302      1
3   9.604341  -5.886795   7.894498  -6.535568  -6.916881      0
4  10.157236  -5.550074   7.488372  -5.385435  -6.902762      0

In [ ]:
x, y = data.iloc[:, :-1], data.iloc[:, -1:] #veri çerçevesinden verileri aldık

In [ ]:
x.head()

ozellik-1  ozellik-2  ozellik-3  ozellik-4  ozellik-5
0  -8.129682  -6.193360   5.296303   8.955262  -3.266606
1   9.705815  -5.275625   6.012196  -5.893469  -6.676234
2  -7.944387  -6.130736   4.100220   9.626914  -4.119302
3   9.604341  -5.886795   7.894498  -6.535568  -6.916881
4  10.157236  -5.550074   7.488372  -5.385435  -6.902762

In [ ]:
y

cikis
0        1
1        0
2        1
3        0
4        0
..     ...
121      1
122      1
123      0
124      0
125      1

[126 rows x 1 columns]

## Datanın KNN algoritması ile sınıflandırılması

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.4, random_state=42) #eğitme verilerini %60, test verilerini %40 olacak şekilde ayırdım

In [ ]:
from sklearn.neighbors import KNeighborsClassifier


In [ ]:
knn = KNeighborsClassifier() #knn kullanacağımı söyledim

In [ ]:
import tensorflow as tf

In [ ]:
tf.squeeze(y_train) #boyutu 1 olan boyutları kaldırır

<tf.Tensor: shape=(75,), dtype=int64, numpy=
array([1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0])>

In [ ]:
model = knn.fit(x_train, tf.squeeze(y_train)) #modeli eğitme verilerine uydurmak için knn kullanacağını söyledim

In [ ]:
model

KNeighborsClassifier()

In [ ]:
y_pred = model.predict(x_test) #gelen veri noktaları sınıfılandırıldı

In [ ]:
y_pred

array([0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1])

In [ ]:
tf.squeeze(y_test)

<tf.Tensor: shape=(51,), dtype=int64, numpy=
array([0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1])>

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
acc = accuracy_score(y_test, y_pred) #doğruluk sınıflandırma puanı

In [ ]:
acc

1.0

In [ ]:
conf = confusion_matrix(y_test, y_pred) #gerçek ve tahmin edilen değerler arasında yer alan ilişkiyi incelemek için

In [ ]:
conf

array([[23,  0],
       [ 0, 28]])

In [ ]:
x.shape[0]

126

## Datanın Yapay sinir ağı ile eğitimi

In [ ]:
model1 = tf.keras.models.Sequential([
                                     tf.keras.layers.Dense(16, activation="relu", input_shape = (5,)),
                                     tf.keras.layers.Dense(8, activation="relu"),
                                     tf.keras.layers.Dense(1, activation="sigmoid"),
]) # yapay sinir ağı ile model üzerindeki eğitim ve çıkarım özellikleri

In [ ]:
model1.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_18 (Dense)            (None, 16)                96        
                                                                 
 dense_19 (Dense)            (None, 8)                 136       
                                                                 
 dense_20 (Dense)            (None, 1)                 9         
                                                                 
Total params: 241
Trainable params: 241
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model1.compile(loss = tf.keras.losses.BinaryCrossentropy(),
               optimizer = tf.keras.optimizers.Adam(),
               metrics = ["accuracy"]) #model katmanları eğitim ve çıkarım özellikleriyle bir nesnede gruplandırır.

In [ ]:
hist = model1.fit(x_train,
                  y_train,
                  epochs = 100,
                  validation_data =(x_test, y_test))

Epoch 1/100
3/3 [==============================] - 1s 89ms/step - loss: 1.0130 - accuracy: 0.5333 - val_loss: 1.0805 - val_accuracy: 0.4510
Epoch 2/100
3/3 [==============================] - 0s 14ms/step - loss: 0.9222 - accuracy: 0.5333 - val_loss: 0.9893 - val_accuracy: 0.4510
Epoch 3/100
3/3 [==============================] - 0s 14ms/step - loss: 0.8361 - accuracy: 0.5333 - val_loss: 0.9091 - val_accuracy: 0.4510
Epoch 4/100
3/3 [==============================] - 0s 17ms/step - loss: 0.7684 - accuracy: 0.5333 - val_loss: 0.8320 - val_accuracy: 0.4510
Epoch 5/100
3/3 [==============================] - 0s 13ms/step - loss: 0.6974 - accuracy: 0.5333 - val_loss: 0.7614 - val_accuracy: 0.4510
Epoch 6/100
3/3 [==============================] - 0s 16ms/step - loss: 0.6396 - accuracy: 0.5333 - val_loss: 0.6952 - val_accuracy: 0.4510
Epoch 7/100
3/3 [==============================] - 0s 16ms/step - loss: 0.5837 - accuracy: 0.5333 - val_loss: 0.6347 - val_accuracy: 0.4510
Epoch 8/100
3/3 [===